# Generated by Django 5.0.2 on 2024-03-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('reader_name', models.CharField(max_length=255)),
                ('loan_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
