# Generated by Django 5.0.2 on 2024-03-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0002_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('book', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
