# Generated by Django 5.0.2 on 2024-05-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0003_loandetail_delete_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('return_date', models.DateField()),
                ('penalty', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
