# Generated by Django 5.0.2 on 2024-05-04 19:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0004_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='book_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
