# Generated by Django 5.0.2 on 2024-05-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0005_record_book_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('page_count', models.IntegerField()),
                ('publish_date', models.DateField()),
                ('book_code', models.CharField(max_length=50, unique=True)),
                ('cover_image', models.ImageField(upload_to='book_covers/')),
                ('additional_images', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
            ],
        ),
    ]
