# Generated by Django 5.0.2 on 2024-05-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0006_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
